env:
  global:
    - CUDA_VERSION: "8.0"
    - CUDA_SHORT_VERSION: "80"

matrix:
  include:
    - sudo: required
      dist: trusty
      services:
        - docker
      env: BUILD="linux"
      addons: {apt: {packages: []}}

    - sudo: required
      dist: trusty
      services:
        - docker
      env: BUILD="source"
      addons: {apt: {packages: []}}

    - language: objective-c
      os: osx
      env: BUILD="osx"
      addons: {apt: {packages: []}}
      osx_image: xcode6.4 # Supported versions: https://docs.travis-ci.com/user/languages/objective-c/#Supported-Xcode-versions

script:
  - if [[ "$BUILD" == "linux" ]]; then

        docker run -e TRAVIS_PULL_REQUEST
            -t -i --rm -v `pwd`:/io jchodera/omnia-build-box:cuda${CUDA_SHORT_VERSION}-amd30-clang38
            bash /io/devtools/travis/linux-build.sh;

    elif [[ "$BUILD" == "source" ]]; then

        docker run -e TRAVIS_PULL_REQUEST
            -t -i --rm -v `pwd`:/io jchodera/omnia-build-box:cuda${CUDA_SHORT_VERSION}-amd30-clang38
            bash /io/devtools/travis/source-build.sh;

    elif [[ "$BUILD" == "osx" ]]; then

        echo "Building osx...";
        bash devtools/travis/osx-build.sh;

    fi

# S3 deployment doesn't do anything right now. Will revive it later.
deploy:
  - provider: s3
    access_key_id:
      secure: "AjE3nuj6kVuf21mOf0aZydW/3S/uCWsaoXC/huRxkxrmsNlnHBNGHZ9N48san1IxZAQM5pyaf7Yo9gkHur9obgq+e3lNgGvPp2mfkNXtLYcLJ46JF4kYliAtutjLWskrLg25Gu3xzF4EQkqSe0Le/oWldWWbTgvvH+KRq/vTHzI="
    secret_access_key:
      secure: "ISDQNSG2t0666PULtffo4wsKLFdu622EzuZxmiTxvLkjQGQlqm5+qn1Gd5UMLk7Ts2E0psdnmSrf6LVVCfrrQO/hcZHiJw3ZslMPDBBlRr8Epwdldn98ULhVoyQKtjXjCPzroa2UZCl1RFs4Nwb/VdDlI490XV0Lp4Woj1AT8tY="
    bucket: "docs.openmm.org"
    skip_cleanup: true
    region: us-west-1
    local_dir: api-docs/
    upload_dir: development
    on:
      branch: master
      condition: '! -z "${DOCS_DEPLOY}" && "${DOCS_DEPLOY}" = "true"'
